import mongoose from 'mongoose';
import Member from '../models/Member.js'; import Attendance from '../models/Attendance.js'; import Payment from '../models/Payment.js'; import Expense from '../models/Expense.js'; import Seat from '../models/Seat.js'; import ActivityLog from '../models/ActivityLog.js'; import Notification from '../models/Notification.js';
const monthStart=()=>new Date(new Date().getFullYear(),new Date().getMonth(),1), dayStart=()=>new Date(new Date().setHours(0,0,0,0)), dayEnd=()=>new Date(new Date().setHours(24,0,0,0)), ago=n=>new Date(new Date().getFullYear(),new Date().getMonth()-n+1,1);
const fill=(rows,n,fields)=>{const map=new Map(rows.map(r=>[r._id.year+'-'+r._id.month,r]));return Array.from({length:n},(_,i)=>{const d=new Date(new Date().getFullYear(),new Date().getMonth()-n+i+1,1),r=map.get(d.getFullYear()+'-'+(d.getMonth()+1))||{};return{month:d.toLocaleString('en',{month:'short'}),year:d.getFullYear(),...Object.fromEntries(fields.map(f=>[f,r[f]||0]))}})};
class DashboardService {
 async adminSummary(){const [totalMembers,activeMembers,present,seats,income,expenses,pending,expiry]=await Promise.all([Member.countDocuments(),Member.countDocuments({status:'Active',membershipExpiryDate:{$gte:new Date()}}),Attendance.distinct('memberId',{date:{$gte:dayStart(),$lt:dayEnd()},status:'Present'}),Seat.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]),Payment.aggregate([{$match:{paymentDate:{$gte:monthStart()},status:'Paid'}},{$group:{_id:null,total:{$sum:'$amount'}}}]),Expense.aggregate([{$match:{expenseDate:{$gte:monthStart()}}},{$group:{_id:null,total:{$sum:'$amount'}}}]),Payment.aggregate([{$match:{status:'Pending'}},{$group:{_id:null,total:{$sum:'$amount'}}}]),Member.countDocuments({status:'Active',membershipExpiryDate:{$gte:new Date(),$lte:new Date(Date.now()+604800000)}})]);const s=Object.fromEntries(seats.map(x=>[x._id.toLowerCase(),x.count]));return{totalMembers,activeMembers,presentToday:present.length,absentToday:Math.max(activeMembers-present.length,0),occupiedSeats:s.occupied||0,availableSeats:s.available||0,monthlyIncome:income[0]?.total||0,monthlyExpenses:expenses[0]?.total||0,pendingFees:pending[0]?.total||0,membershipExpiry:expiry}}
 async attendance(n=6){const rows=await Attendance.aggregate([{$match:{date:{$gte:ago(n)}}},{$group:{_id:{year:{$year:'$date'},month:{$month:'$date'}},present:{$sum:{$cond:[{$eq:['$status','Present']},1,0]}},absent:{$sum:{$cond:[{$eq:['$status','Absent']},1,0]}},late:{$sum:{$cond:[{$and:[{$eq:['$status','Present']},{$gte:[{$hour:'$checkInTime'},10]}]},1,0]}}}}]);return fill(rows,n,['present','absent','late'])}
 async monthly(model,date,key,n,match={}){const rows=await model.aggregate([{$match:{...match,[date]:{$gte:ago(n)}}},{$group:{_id:{year:{$year:'$'+date},month:{$month:'$'+date}},[key]:{$sum:'$amount'}}}]);return fill(rows,n,[key])}
 revenue(n=12){return this.monthly(Payment,'paymentDate','income',n,{status:'Paid'})} expenses(n=12){return this.monthly(Expense,'expenseDate','expense',n)} occupancy(){return Seat.aggregate([{$group:{_id:'$status',value:{$sum:1}}},{$project:{_id:0,name:'$_id',value:1}}])}
 async growth(n=12){const rows=await Member.aggregate([{$match:{joiningDate:{$gte:ago(n)}}},{$group:{_id:{year:{$year:'$joiningDate'},month:{$month:'$joiningDate'}},members:{$sum:1}}}]);return fill(rows,n,['members'])}
 activity(n=10){return ActivityLog.find().sort({timestamp:-1}).limit(n).populate('userId','name profileImage').lean()} expiring(n=10){return Member.find({status:'Active',membershipExpiryDate:{$gte:new Date(),$lte:new Date(Date.now()+604800000)}}).sort('membershipExpiryDate').limit(n).populate('seatId','seatNumber').populate('shiftId','shiftName').lean()}
 async member(userId){const m=await Member.findOne({userId}).populate('seatId','seatNumber').populate('shiftId','shiftName').lean();if(!m){const e=new Error('Student profile not found');e.statusCode=404;throw e}return m}
 async userSummary(id){const m=await this.member(id);const [a,p,last,today]=await Promise.all([Attendance.aggregate([{$match:{memberId:m._id,date:{$gte:monthStart()}}},{$group:{_id:'$status',count:{$sum:1}}}]),Payment.aggregate([{$match:{memberId:m._id,status:'Pending'}},{$group:{_id:null,total:{$sum:'$amount'}}}]),Payment.findOne({memberId:m._id,status:'Paid'}).sort({paymentDate:-1}).lean(),Attendance.findOne({memberId:m._id,date:{$gte:dayStart(),$lt:dayEnd()}}).lean()]);const c=Object.fromEntries(a.map(x=>[x._id.toLowerCase(),x.count])),total=(c.present||0)+(c.absent||0);return{seatNumber:m.seatId?.seatNumber||'Unassigned',shift:m.shiftId?.shiftName||'Unassigned',todayAttendance:today?.status||'Not marked',membershipStatus:m.status==='Active'&&m.membershipExpiryDate>=new Date()?'Active':'Expired',remainingDays:Math.max(Math.ceil((m.membershipExpiryDate-new Date())/86400000),0),pendingFees:p[0]?.total||0,lastPayment:last?{date:last.paymentDate,amount:last.amount}:null,attendancePercentage:total?Math.round(c.present/total*100):0}}
 async userAttendance(id){const m=await this.member(id),records=await Attendance.find({memberId:m._id,date:{$gte:monthStart()}}).sort('date').lean(),presentDays=records.filter(r=>r.status==='Present').length,absentDays=records.filter(r=>r.status==='Absent').length;return{presentDays,absentDays,percentage:records.length?Math.round(presentDays/records.length*100):0,records}}
 async membership(id){const m=await this.member(id);return{joiningDate:m.joiningDate,plan:m.membershipPlan,expiryDate:m.membershipExpiryDate,remainingDays:Math.max(Math.ceil((m.membershipExpiryDate-new Date())/86400000),0),status:m.status}} notifications(id){return Notification.find({$or:[{recipientId:new mongoose.Types.ObjectId(id)},{recipientRole:'Student'},{recipientRole:'All'}]}).sort({createdAt:-1}).limit(20).lean()}
} export default new DashboardService();